version: "3.9"

services:
  url_shortener:
    depends_on:
      - postgres
    container_name: url_shortener
    hostname: url_shortener
    networks:
      - my_network
    ports:
      - "8080:8080"
    build:
      context: .
    environment:
      - POSTGRES_USER=go_user
      - POSTGRES_PASSWORD=8246go
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=url_storage
    deploy:
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    networks:
      - my_network
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=url_storage
      - POSTGRES_USER=go_user
      - POSTGRES_PASSWORD=8246go
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U go_user -d url_storage"]
      interval: 10s
      timeout: 45s
      retries: 10
    restart: always

volumes:
  postgres_storage:

networks:
  my_network:
    driver: bridge
